config/routes.rb
Obnov::Application.routes.draw do
  devise_for :users

  resources :projects, :controller => 'streams', :as => 'streams' do
    resources :posts do
      resources :comments
    end
    
    resources :members
  end
  
  root :to => "pages#index"

end

app/models/stream.rb
class Stream
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name
  field :slug
  referenced_in :user, :inverse_of => :owned_streams
  references_and_referenced_in_many :members, :class_name => 'User', :inverse_of => :streams
  references_and_referenced_in_many :applicants, :class_name => 'User', :inverse_of => :pending_streams
  references_many :posts
  after_create :add_owner_to_members
  
  validates_format_of :slug, :with => /[A-Za-z0-9-]/
  validates_uniqueness_of :slug
  
  def to_param
    self.slug
  end
  
  def self.find_by_slug(slug)
    find(:first, :conditions => { :slug => slug })
  end
  
  def is_applicant?(user)
    self.applicants.include? user
  end
  
  def accept_application(user)
    self.applicants.delete user
    self.members.push user
    self.save
  end
  
  def decline_application(user)
    self.applicants.delete user
    self.save
  end
  
  protected
  
  def add_owner_to_members
    self.members.push self.user
    self.save
  end
  
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @streams = current_user.streams
  end

  def show
    @stream = Stream.find_by_slug(params[:id])
    @post = Post.new
    @pipe = {
      :stream_id => @stream.id.to_s
    }
  end

  def new
    @stream = Stream.new
  end

  def edit
    @stream = Stream.find_by_slug(params[:id])
    authorize! :edit, @stream
  end

  def create
    @stream = Stream.new(params[:stream])
    @stream.user = current_user

    if @stream.save
      redirect_to(@stream, :notice => 'Stream was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @stream = Stream.find_by_slug(params[:id])
    authorize! :update, @stream

    if @stream.update_attributes(params[:stream])
      redirect_to(@stream, :notice => 'Stream was successfully updated.')
    else
      render :action => "edit" 
    end
  end

  def destroy
    @stream = Stream.find_by_slug(params[:id])
    authorize! :destroy, @stream
    @stream.destroy
    redirect_to(streams_url)
  end
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/streams/_form.html.haml
= form_for(@stream) do |f|
  - if @stream.errors.any?
    #error_explanation
      %h2
        = pluralize(@stream.errors.count, "error")
        prohibited this stream from being saved:
      %ul
        - @stream.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/streams/_form.html.slim
= form_for(@stream) do |f|
  - if @stream.errors.any?
    #error_explanation
      h2
        = pluralize(@stream.errors.count, "error")
        | prohibited this stream from being saved:
      ul
        - @stream.errors.full_messages.each do |msg|
          li= msg
  .field
    = f.label :name, 'Название'
    br
    = f.text_field :name
    
  .field
    = f.label :name, 'Адрес'
    br
    = f.text_field :slug
    
  .actions
    button type="submit" style="margin-right: 10px"
      | Сохранить
    - unless @stream.new_record?
      = link_to 'Удалить', @stream, :method => :delete, :class => 'negative'

app/views/streams/edit.html.slim
h1 Редактирование проекта
= render 'form'

app/views/streams/index.html.haml
%h1 Потоки

%ul#streams
- @streams.each do |stream|
  %li.stream
    = link_to stream.name, stream
%br

= link_to 'Новый поток', new_stream_path

app/views/streams/index.html.slim
h1 Проекты

ul#streams
  - @streams.each do |stream|
    li.stream
      = link_to stream.name, stream
br

= link_to new_stream_path, :class => 'primary button' do
  span class="plus icon" 
  | Создать проект

app/views/streams/new.html.slim
h1 Создание проекта
= render 'form'

app/views/streams/show.html.haml
%p#notice= notice
%h1
  = @stream.name
= link_to 'Редактировать', edit_stream_path(@stream)
|
= link_to 'Все потоки', streams_path

= form_for([@stream, @post]) do |f|
  .field
    = f.text_field :content
  .actions
    = f.submit 'Опубликовать'


#updates
  - @stream.posts.activity.each do |post|
    .post
      = link_to '#', [@stream, post]
      [
      = link_to post.comments.count, [@stream, post]
      ]
      = post.content
      %small
        = time_ago_in_words(post.created_at)

app/views/streams/show.html.slim
- if notice
  p#notice= notice
  
#stream
  h1
    = @stream.name

  - if can? :read, @stream
    .members
      = link_to stream_members_path(@stream), :class => 'left button' do
        | Участники
      - if @stream.applicants.count > 0
        small style="color: #f70; font-weight: bold"
          = " +#{@stream.applicants.count}"
  - if can? :manage, @stream
    .edit
      = link_to edit_stream_path(@stream), :class => 'right button' do
        span class="pen icon"
        | Редактировать

  .clear

  - if can? :read, @stream
    = form_for([@stream, @post]) do |f|
      .field
        = f.text_area :content
      .actions
        button type="submit" class="primary positive"
          | Опубликовать


    #posts
      = render @stream.posts.activity
      
  - else
    - if @stream.is_applicant? current_user
      div
        | Ваша заявка на присоединение к проекту находится на рассмотрении.
    - else
      div style="padding-bottom: 10px"
        | Вы не можете просматривать проект, т. к. не являетесь его участником.
      = form_tag stream_members_path(@stream), :method => :post do
        button class='positive button' 
          span class='rightarrow icon'
          | Присоединиться
      