config/routes.rb
Obnov::Application.routes.draw do
  devise_for :users

  resources :projects, :controller => 'streams', :as => 'streams' do
    resources :posts do
      resources :comments
    end
    
    resources :members
  end
  
  root :to => "pages#index"

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @stream = Stream.find_by_slug(params[:stream_id])
    authorize! :read, @stream
  end

  def create
    @stream = Stream.find_by_slug(params[:stream_id])
    unless @stream.is_applicant? current_user
      @stream.applicants << current_user 
      @stream.save
    end
    
    redirect_to(@stream, :notice => 'Заявка добавлена на рассмотрение.')
  end
  
  def update
    @stream = Stream.find_by_slug(params[:stream_id])
    @user = User.find(params[:id])
    authorize! :manage, @stream
    
    if @stream.is_applicant? @user
      @stream.accept_application @user
    end
    
    redirect_to stream_members_path(@stream)
  end

  def destroy
    @stream = Stream.find_by_slug(params[:stream_id])
    @user = User.find(params[:id])
    authorize! :manage, @stream
    
    @stream.applicants.delete @user
    @stream.members.delete @user
    @stream.save
    
    redirect_to stream_members_path(@stream)
  end

end

app/views/members/_member.html.slim
.user
  .avatar
    = gravatar_for member
  .info style="float:left"
    div
      span.author
        = member.name
      span style="margin-left: 10px"
      - if is_applicant
        em кандидат
      - elsif member == @stream.user
        em владелец проекта
    div 
      = member.email
    - if can? :manage, @stream and member != @stream.user
      div style="padding-top: 2px"
        - if is_applicant
          = link_to 'Принять', stream_member_path(@stream, member), :method => :put, :class => 'positive', :style => 'margin-right: 2px' 
          = link_to 'Отклонить', stream_member_path(@stream, member), :method => :delete, :class => 'negative'
        - else
          = link_to 'Отключить', stream_member_path(@stream, member), :method => :delete, :class => 'negative'
  .clear

app/views/members/index.html.slim
p#notice= notice
h1
  = link_to @stream.name, @stream
  = raw ' &mdash; Участники'

#members
  - @stream.applicants.each do |user|
    = render :partial => 'member', :object => user, :locals => { :is_applicant => true }

  - @stream.members.each do |user|
    = render :partial => 'member', :object => user, :locals => { :is_applicant => false }